# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network :private_network, ip: "192.168.33.99"
  config.vm.network :forwarded_port, guest: 22, host: 2299
  config.vm.network :forwarded_port, guest: 80, host: 8099
  config.vm.network :forwarded_port, guest: 443, host: 44399
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.landrush.enabled = true

  config.vm.post_up_message = <<-EOH
  
  EOH

  config.vm.define 'ubuntu1404.vagrant.dev' do |instance|
    config.vm.hostname = 'ubuntu1404.vagrant.dev'
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    # Every Vagrant virtual environment requires a box to build off of.
    instance.vm.box = 'ubuntu1404-amd64'

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    instance.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

    # View the documentation for the provider you're using for more
    # information on available options.
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbooks/hacking.yml"
      ansible.verbose = 'vv'
      ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
      ansible.inventory_path = "../ansible/inventory/hosts"
      #ansible.tags = 'hacking' # Use this after the first run to speed things up a bit
    end
  end
end
