---

##
## Configure Jenkins Jobs
##

## This uses jenkins-job-builder
## http://ci.openstack.org/jenkins-job-builder/
## Inspiration from https://github.com/Azulinho/ansible-jenkins-showcase

# Clone the jenkins-job-builder repos, these are the repos full of definitions of Jenkins jobs.
# The jobs change frequently and should be part of a CD pipeline if possible to provide self-service
# job management.
# TODO: Should we check for the github.key in /etc/ssh/ssh_known_hosts?
- name: Clone jenkins-job-builder repos full of job definitions
  git:
    repo: '{{ item.repo }}'
    dest: '{{ jenkins_ext_job_builder_repos_dir }}/{{ item.name }}'
    update: True
    accept_hostkey: True
    version: '{{ item.version | default("HEAD") }}'
  register: jenkins_job_builder_git_clone
  with_flattened:
    - jenkins_job_builder_repos

- name: Run jenkins-job-builder against the configured instance
  shell: "{{ jenkins_job_builder }} update {{ jenkins_ext_job_builder_repos_dir }}/{{ item.0.name }}/{{ item.0.jobs_dir }} {{ item.1 }}"
  with_subelements:
    - jenkins_job_builder_repos
    - filters
  when: jenkins_job_builder_git_clone is defined and
        jenkins_job_builder_git_clone.changed
