---

##
## Configure Jenkins Core
##

- name: Ensure jenkins_ext_groovy_root exists
  file:
    path: '{{ jenkins_ext_groovy_root }}'
    state: directory

- name: Generate Groovy Script template for global security and admin user
  template:
    src: 'groovy/{{ item }}.groovy.j2'
    dest: '{{ jenkins_ext_groovy_root }}/{{ item }}.groovy'
  with_flattened:
    - check_if_security_is_enabled # Individual script used below
    - set_global_security_and_add_admin_user # Individual script used below
    - jenkins_groovy_scripts
    - jenkins_group_groovy_scripts
    - jenkins_host_groovy_scripts

- name: Test if Auth is configured
  command: '{{ jenkins_cli }} groovy {{ jenkins_ext_groovy_root }}/{{ item }}.groovy'
  register: jenkins_auth_result
  with_items:
    - check_if_security_is_enabled
  failed_when: ( jenkins_auth_result.stderr != "" ) and
               ( 'hudson.security.AccessDeniedException2' not in jenkins_auth_result.stderr )
  changed_when: False
  when: jenkins_auth is defined and jenkins_auth

- name: Configure auth if it is not configured...
  command: '{{ jenkins_cli }} groovy {{ jenkins_ext_groovy_root }}/{{ item }}.groovy'
  register: jenkins_configure_auth_result
  with_items:
    - set_global_security_and_add_admin_user
  when: ( jenkins_auth_result is defined ) and
        ( 'hudson.security.AccessDeniedException2' not in jenkins_auth_result.stderr )

- name: Login to Jenkins for the next task to run groovy
  command: '{{ jenkins_cli }} login --username {{ jenkins_service_user }} --password {{ jenkins_service_password }}'
  register: jenkins_cli_login
  changed_when: False
  when: jenkins_configure_auth_result is defined

- name: Run Groovy scripts using jenkins-cli
  command: '{{ jenkins_cli }} groovy {{ jenkins_ext_groovy_root }}/{{ item }}.groovy'
  changed_when: False
  with_flattened:
    - jenkins_groovy_scripts
    - jenkins_group_groovy_scripts
    - jenkins_host_groovy_scripts

- name: Logout of Jenkins
  command: '{{ jenkins_cli }} logout'
  changed_when: False
  when: jenkins_cli_login is defined
