---

# Install Jenkins
- { include: install.yml, tags: jenkins-install }

# Configure Jenkins Core
- { include: configure_core.yml, tags: jenkins-core }

# Configure Jenkins Plugins
- { include: configure_plugins.yml, tags: jenkins-plugins }

# Configure Jenkins Jobs
- { include: configure_jobs.yml, tags: jenkins-jobs }
