---

# Common prerequsites
- { include: common.yml, jenkins-common }

# Install and Configure Jenkins according to the defined role
- { include: server.yml, when: jenkins_role == 'server', tags: jenkins-server }
- { include: slave.yml,  when: jenkins_role == 'slave', tags: jenkins-slave }

